package view;

import java.awt.List;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paloma
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblClassificacao = new javax.swing.JLabel();
        lblDataEntrada = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        lblGanho = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfClassificacao = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        tfData = new javax.swing.JTextField();
        btnGanho = new javax.swing.JButton();
        btnGastos = new javax.swing.JButton();
        tfDataCadastro = new javax.swing.JTextField();
        lblData1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbprodutos = new javax.swing.JTable();
        btnRecebidos = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        btnSaldo = new javax.swing.JButton();
        lblRecebidos = new javax.swing.JLabel();
        btnDespesas = new javax.swing.JButton();
        lblDespesas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle Financeiro");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(57, 158, 158));

        lblNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNome.setText("Nome:");

        lblValor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblValor.setText("Valor:");

        lblClassificacao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblClassificacao.setText("Classificação:");

        lblDataEntrada.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDataEntrada.setText("Data Entrada:");

        btnCadastro.setBackground(new java.awt.Color(217, 232, 255));
        btnCadastro.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCadastro.setText("Cadastrar");
        btnCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastro.setBorderPainted(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(217, 232, 255));
        btnAtualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 51, 153));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtualizar.setBorderPainted(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnApagar.setBackground(new java.awt.Color(217, 232, 255));
        btnApagar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApagar.setBorderPainted(false);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        lblGanho.setBackground(new java.awt.Color(0, 204, 153));

        tfNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfNome.setText("Recebimento");
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfClassificacao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfClassificacao.setText("Salário");
        tfClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClassificacaoActionPerformed(evt);
            }
        });

        tfValor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfValor.setText("1500");
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        tfData.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfData.setText("09/10/2024");

        btnGanho.setBackground(new java.awt.Color(51, 153, 0));
        btnGanho.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGanho.setForeground(new java.awt.Color(255, 255, 255));
        btnGanho.setText("Ganho(+)");
        btnGanho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGanho.setBorderPainted(false);

        btnGastos.setBackground(new java.awt.Color(204, 51, 0));
        btnGastos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGastos.setForeground(new java.awt.Color(255, 255, 255));
        btnGastos.setText("Gastos(-)");
        btnGastos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGastos.setBorderPainted(false);

        tfDataCadastro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfDataCadastro.setText("09/10/2024");

        lblData1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblData1.setText("Cadastro:");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de Controle Financeiro ");

        btnSalvar.setBackground(new java.awt.Color(217, 232, 255));
        btnSalvar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 51, 153));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.setBorderPainted(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblValor)
                                .addGap(18, 18, 18)
                                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblClassificacao)
                                .addGap(18, 18, 18)
                                .addComponent(tfClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGanho)
                        .addGap(566, 566, 566)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGanho, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblData1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDataEntrada)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblGanho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblData1)
                                    .addComponent(tfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataEntrada)
                                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblClassificacao)
                                    .addComponent(tfClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGanho, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblValor)
                                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
        );

        tbprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Classificação", "Valor", "Data", "Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbprodutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbprodutos);

        btnRecebidos.setBackground(new java.awt.Color(217, 232, 255));
        btnRecebidos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnRecebidos.setForeground(new java.awt.Color(0, 51, 153));
        btnRecebidos.setText("Valores recebidos:");
        btnRecebidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRecebidos.setBorderPainted(false);
        btnRecebidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebidosActionPerformed(evt);
            }
        });

        lblSaldo.setText("R$");

        btnSaldo.setBackground(new java.awt.Color(217, 232, 255));
        btnSaldo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSaldo.setForeground(new java.awt.Color(0, 51, 153));
        btnSaldo.setText("Saldo disponível");
        btnSaldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaldo.setBorderPainted(false);
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        lblRecebidos.setText("R$");

        btnDespesas.setBackground(new java.awt.Color(217, 232, 255));
        btnDespesas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnDespesas.setForeground(new java.awt.Color(0, 51, 153));
        btnDespesas.setText("Total de Despesas");
        btnDespesas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDespesas.setBorderPainted(false);
        btnDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespesasActionPerformed(evt);
            }
        });

        lblDespesas.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecebidos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecebidos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecebidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRecebidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        DefaultTableModel tbProdutos = (DefaultTableModel) tbprodutos.getModel();

        // Criando um array de objetos com os dados que você deseja adicionar à tabela
        Object[] dados = {
            tfNome.getText(),
            tfClassificacao.getText(),
            tfValor.getText(),
            tfData.getText(),
            tfDataCadastro.getText()
        };

        // Adicionando a nova linha à tabela
        tbProdutos.addRow(dados);
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add youndling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        int selectedRow = tbprodutos.getSelectedRow();

        if (selectedRow != -1) {
            DefaultTableModel tbProdutos = (DefaultTableModel) tbprodutos.getModel();
            tbProdutos.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada para remover.");
        }


    }//GEN-LAST:event_btnApagarActionPerformed

    private void tbprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbprodutosMouseClicked

        if (tbprodutos.getSelectedRow() != -1) {
            tfNome.setText(tbprodutos.getValueAt(tbprodutos.getSelectedRow(), 0).toString());
            tfClassificacao.setText(tbprodutos.getValueAt(tbprodutos.getSelectedRow(), 1).toString());
            tfValor.setText(tbprodutos.getValueAt(tbprodutos.getSelectedRow(), 2).toString());
            tfData.setText(tbprodutos.getValueAt(tbprodutos.getSelectedRow(), 3).toString());
            tfDataCadastro.setText(tbprodutos.getValueAt(tbprodutos.getSelectedRow(), 4).toString());
        }

    }//GEN-LAST:event_tbprodutosMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRecebidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebidosActionPerformed
        DefaultTableModel tbProdutos = (DefaultTableModel) tbprodutos.getModel();
        double totalRecebidos = 0.0;

        String[] categoriasRecebidos = {
            "Salário",
            "Renda extra",
            "Mesada",
            "Frelancer"

        };

        for (int i = 0; i < tbProdutos.getRowCount(); i++) {
            String classificacao = (String) tbProdutos.getValueAt(i, 1); // Coluna 1: Classificação
            String valorStr = (String) tbProdutos.getValueAt(i, 2); // Coluna 2: Valor

            for (String categoria : categoriasRecebidos) {
                if (classificacao.equalsIgnoreCase(categoria)) {
                    try {
                        double valor = Double.parseDouble(valorStr);
                        totalRecebidos += valor;
                    } catch (NumberFormatException e) {
                        System.out.println("Erro ao converter valor: " + valorStr);
                    }
                    break;
                }
            }
        }

        lblRecebidos.setText(" R$ " + String.format("%.2f", totalRecebidos));


    }//GEN-LAST:event_btnRecebidosActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
      
        double totalRecebidos = 0.0;
        double totalDespesas = 0.0;

   
        String[] categoriasRecebidos = {
            "Salário",
            "Renda extra",
            "Mesada",
            "Freelancer"
        };

        DefaultTableModel tbProdutos = (DefaultTableModel) tbprodutos.getModel();
        for (int i = 0; i < tbProdutos.getRowCount(); i++) {
            String classificacao = (String) tbProdutos.getValueAt(i, 1); // Coluna 1: Classificação
            String valorStr = (String) tbProdutos.getValueAt(i, 2); // Coluna 2: Valor

            for (String categoria : categoriasRecebidos) {
                if (classificacao.equalsIgnoreCase(categoria)) {
                    try {
                        double valor = Double.parseDouble(valorStr);
                        totalRecebidos += valor;
                    } catch (NumberFormatException e) {
                        System.out.println("Erro ao converter valor: " + valorStr);
                    }
                    break;
                }
            }
        }

        // Calcular totalDespesas
        String[] categoriasDespesas = {
            "Alimentação",
            "Automóvel",
            "Saúde",
            "Bem estar",
            "Investimento",
            "Outros",
            "Compras",
            "Casa"
        };

        for (int i = 0; i < tbProdutos.getRowCount(); i++) {
            String classificacao = (String) tbProdutos.getValueAt(i, 1); // Coluna 1: Classificação
            String valorStr = (String) tbProdutos.getValueAt(i, 2); // Coluna 2: Valor

            for (String categoria : categoriasDespesas) {
                if (classificacao.equalsIgnoreCase(categoria)) {
                    try {
                        double valor = Double.parseDouble(valorStr);
                        totalDespesas += valor;
                    } catch (NumberFormatException e) {
                        System.out.println("Erro ao converter valor: " + valorStr);
                    }
                    break;
                }
            }
        }

        double saldoDisponivel = totalRecebidos - totalDespesas;

        lblSaldo.setText("R$ " + String.format("%.2f", saldoDisponivel));
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespesasActionPerformed

        DefaultTableModel tbProdutos = (DefaultTableModel) tbprodutos.getModel();
        double totalDespesas = 0.0;

        String[] categoriasDespesas = {
            "Alimentação",
            "Automóvel",
            "Saúde",
            "Bem estar",
            "Investimento",
            "Outros",
            "Compras",
            "Casa"
        };

        for (int i = 0; i < tbProdutos.getRowCount(); i++) {
            String classificacao = (String) tbProdutos.getValueAt(i, 1); // Coluna 1: Classificação
            String valorStr = (String) tbProdutos.getValueAt(i, 2); // Coluna 2: Valor

            for (String categoria : categoriasDespesas) {
                if (classificacao.equalsIgnoreCase(categoria)) {
                    try {
                        double valor = Double.parseDouble(valorStr);
                        totalDespesas += valor;
                    } catch (NumberFormatException e) {
                        System.out.println("Erro ao converter valor: " + valorStr);
                    }
                    break;
                }
            }
        }

        lblDespesas.setText(" R$ " + String.format("%.2f", totalDespesas));


    }//GEN-LAST:event_btnDespesasActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (tbprodutos.getSelectedRow() != -1) {
            tbprodutos.setValueAt(tfNome.getText(), tbprodutos.getSelectedRow(), 0);
            tbprodutos.setValueAt(tfClassificacao.getText(), tbprodutos.getSelectedRow(), 1);
            tbprodutos.setValueAt(tfValor.getText(), tbprodutos.getSelectedRow(), 2);
            tbprodutos.setValueAt(tfData.getText(), tbprodutos.getSelectedRow(), 3);
            tbprodutos.setValueAt(tfDataCadastro.getText(), tbprodutos.getSelectedRow(), 4);

        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tfClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClassificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClassificacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnDespesas;
    private javax.swing.JButton btnGanho;
    private javax.swing.JButton btnGastos;
    private javax.swing.JButton btnRecebidos;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblDespesas;
    private javax.swing.JLabel lblGanho;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRecebidos;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tbprodutos;
    private javax.swing.JTextField tfClassificacao;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfDataCadastro;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
